spring:
  application:
    name: demo
  profiles:
    active: dev
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo
    username: admin
    password: admin
logging:
  level:
    org.springframework.data.r2dbc: Debug